{
 "title": "Camunda Pizza Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Completed Pizza Orders", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pizza Delivered",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 1, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "camunda_pizza_delivered", "legendFormat": "{{type}}" }
   ]
  },
  {
   "title": "Pizza Delivery Succes",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 11, "x": 12, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    { "expr": "sum(camunda_pizza_delivered)" }
   ]
  },
  {
   "title": "Rejected Orders",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 11, "x": 12, "y": 5 },
   "format": "short",
   "valueName": "current",
   "targets": [
    { "expr": "camunda_pizza_rejected" }
   ]
  },
  { "title": "Cases", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Open Cases",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "camunda_open_cases" }
   ]
  },
  {
   "title": "Closed Cases",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "camunda_closed_cases" }
   ]
  },
  { "title": "User Tasks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Active Unassigned User Tasks Count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "camunda_active_unassigned_user_tasks_count"
    }
   ]
  },
  {
   "title": "Active User Tasks",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "camunda_active_user_tasks_count"
    }
   ]
  },
  {
   "title": "Completed User Tasks",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "camunda_complete_user_tasks_count"
    }
   ]
  },
  { "title": "Activity Instances", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Activity Instance Start/End Rate per 1min",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(camunda_metric_job_execution_rejected[1m])",
     "legendFormat": "Execution Rejections"
    },
    {
     "expr": "rate(camunda_metric_activity_instance_start[1m])",
     "legendFormat": "Instance Start"
    },
    {
     "expr": "rate(camunda_metric_activity_instance_end[1m])",
     "legendFormat": "Instance End"
    }
   ]
  },
  {
   "title": "Activity Instance Start (Flow Node Instances)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 27 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "camunda_metric_activity_instance_start"
    }
   ]
  },
  {
   "title": "Activity Instance End",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 7, "x": 7, "y": 27 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "camunda_metric_activity_instance_end"
    }
   ]
  },
  {
   "title": "Job Execution Rejected",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 7, "x": 14, "y": 27 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "camunda_metric_job_execution_rejected"
    }
   ]
  },
  { "title": "Job Execution", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Jobs Successful Executed",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 31 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "camunda_metric_job_successful" }
   ]
  },
  {
   "title": "Jobs Locked (Exclusive)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 7, "x": 7, "y": 31 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "camunda_metric_job_locked_exclusive"
    }
   ]
  },
  {
   "title": "Jobs Failed to Execute",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 7, "x": 14, "y": 31 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "camunda_metric_job_failed" }
   ]
  },
  { "title": "Job Acquisition", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Job Acquisition Attempts",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 35 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "camunda_metric_job_acquisition_attempt"
    }
   ]
  },
  {
   "title": "Jobs Successfully Acquired",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 7, "x": 7, "y": 35 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "camunda_metric_job_acquired_success"
    }
   ]
  },
  {
   "title": "Job Acquire Failure",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 7, "x": 14, "y": 35 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "camunda_metric_job_acquired_failure"
    }
   ]
  },
  { "title": "Decision Execution (DMN)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Decision Elements Executed",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 39 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "camunda_metric_executed_decision_elements"
    }
   ]
  }
 ]
}